<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-04 at 15:32:15.
 */
class UtilityTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Utility
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Utility;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Utility::checkUser
     * @todo   Implement testCheckUser().
     */
    public function testCheckUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Utility::readDbInfo
     * @todo   Implement testReadDbInfo().
     */
    public function testReadDbInfo() {
        $db_info = Utility::readDbInfo();
        $this->assertEquals(4, sizeof($db_info));
    }

}
